-- MySQL Script generated by MySQL Workbench
-- seg 31 mai 2021 11:28:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_sb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_sb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sb` ;
USE `db_sb` ;

-- -----------------------------------------------------
-- Table `db_sb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sb`.`tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `tipo` ENUM('Administrador', 'Cliente') NOT NULL DEFAULT 'Cliente',
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sb`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sb`.`tb_categoria_doenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sb`.`tb_categoria_doenca` (
  `id_categoria_doenca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `transmissivel` TINYINT NOT NULL,
  PRIMARY KEY (`id_categoria_doenca`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sb`.`tb_categoria_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sb`.`tb_categoria_produto` (
  `fk_produto` INT NOT NULL,
  `fk_categoria` INT NOT NULL,
  PRIMARY KEY (`fk_produto`, `fk_categoria`),
  INDEX `fk_tb_categoria_doenca_has_tb_produto_tb_produto1_idx` (`fk_categoria` ASC) VISIBLE,
  INDEX `fk_tb_categoria_doenca_has_tb_produto_tb_categoria_doenca_idx` (`fk_produto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_categoria_doenca_has_tb_produto_tb_categoria_doenca`
    FOREIGN KEY (`fk_produto`)
    REFERENCES `db_sb`.`tb_categoria_doenca` (`id_categoria_doenca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_categoria_doenca_has_tb_produto_tb_produto1`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `db_sb`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sb`.`tb_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sb`.`tb_venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `fk_usuario` INT NOT NULL,
  `fk_produto` INT NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_venda`, `fk_usuario`, `fk_produto`),
  INDEX `fk_tb_usuario_has_tb_produto_tb_produto1_idx` (`fk_produto` ASC) VISIBLE,
  INDEX `fk_tb_usuario_has_tb_produto_tb_usuario1_idx` (`fk_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuario_has_tb_produto_tb_usuario1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `db_sb`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuario_has_tb_produto_tb_produto1`
    FOREIGN KEY (`fk_produto`)
    REFERENCES `db_sb`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
