-- MySQL Script generated by MySQL Workbench
-- Tue Jun  8 10:05:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_sb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_sb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sb` ;
USE `db_sb` ;

-- -----------------------------------------------------
-- Table `db_sb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sb`.`tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `apelido` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `tipo` ENUM('Administrador', 'Cliente') NOT NULL DEFAULT 'Cliente',
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sb`.`tb_medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sb`.`tb_medicamento` (
  `id_medicamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `categoria` ENUM('Referencia', 'Generico', 'Similar') NOT NULL,
  PRIMARY KEY (`id_medicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sb`.`tb_doenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sb`.`tb_doenca` (
  `id_doenca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `transmissivel` TINYINT NOT NULL,
  PRIMARY KEY (`id_doenca`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sb`.`tb_medicamento_doenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sb`.`tb_medicamento_doenca` (
  `fk_medicamento` INT NOT NULL,
  `fk_doenca` INT NOT NULL,
  PRIMARY KEY (`fk_medicamento`, `fk_doenca`),
  INDEX `fk_tb_categoria_doenca_has_tb_produto_tb_produto1_idx` (`fk_doenca` ASC) VISIBLE,
  INDEX `fk_tb_categoria_doenca_has_tb_produto_tb_categoria_doenca_idx` (`fk_medicamento` ASC) VISIBLE,
  CONSTRAINT `fk_tb_categoria_doenca_has_tb_produto_tb_categoria_doenca`
    FOREIGN KEY (`fk_medicamento`)
    REFERENCES `db_sb`.`tb_doenca` (`id_doenca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_categoria_doenca_has_tb_produto_tb_produto1`
    FOREIGN KEY (`fk_doenca`)
    REFERENCES `db_sb`.`tb_medicamento` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sb`.`tb_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sb`.`tb_venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `fk_usuario` INT NOT NULL,
  `fk_medicamento` INT NOT NULL,
  `endereco` VARCHAR(255) NULL,
  `data` DATE NOT NULL,
  `quantidade` INT(50) NOT NULL,
  `status` ENUM('aguardando', 'pago', 'entregue', 'cancelado') NOT NULL,
  PRIMARY KEY (`id_venda`, `fk_usuario`, `fk_medicamento`),
  INDEX `fk_tb_usuario_has_tb_produto_tb_produto1_idx` (`fk_medicamento` ASC) VISIBLE,
  INDEX `fk_tb_usuario_has_tb_produto_tb_usuario1_idx` (`fk_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuario_has_tb_produto_tb_usuario1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `db_sb`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuario_has_tb_produto_tb_produto1`
    FOREIGN KEY (`fk_medicamento`)
    REFERENCES `db_sb`.`tb_medicamento` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
